# Reference: https://spacelift.io/blog/kubernetes-secrets
# Reference: https://kubernetes.io/docs/concepts/workloads/pods/

apiVersion: v1
kind: Pod
metadata:
  name: mysql
  namespace: sqldb
spec:
  containers:
  - name: mysql
    image: 749333546656.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql-image:v1.0
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secret
            key: password
    ports:
      - containerPort: 3306
        name: mysql