# Reference: https://spacelift.io/blog/kubernetes-secrets
# Reference: https://kubernetes.io/docs/concepts/workloads/pods/


apiVersion: v1
kind: Pod
metadata:
  name: employee
  namespace: webapp
spec:
  containers:
  - name: employee
    image: 749333546656.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp-image:v1.0
    ports:
    - containerPort: 8080
    env:
      - name: DBHOST
        value: 10.244.0.20
      - name: DBPORT
        value: "3306"
      - name: DBPWD
        valueFrom:
          secretKeyRef:
            name: webapp-secret
            key: password