# Reference: Week5 ppt

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs
  namespace: sqldb
  labels:
    app: mysqldb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysqldb
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
      - name: mysql
        image: 749333546656.dkr.ecr.us-east-1.amazonaws.com/clo835-mysql-image:v1.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
