# Reference: Week5 ppt

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp-rs
  namespace: webapp
  labels:
    app: employees
    version: v1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
      version: v1
  template:
    metadata:
      labels:
        app: employees
        version: v1
    spec:
      containers:
        - name: webapp
          image: 749333546656.dkr.ecr.us-east-1.amazonaws.com/clo835-webapp-image:v1.0
          ports:
            - containerPort: 8080
          env:
            - name: DBHOST
              value: "mysql-service.sqldb.svc.cluster.local"
            - name: DBPORT
              value: "3306"
            - name: DBPWD
              valueFrom:
                secretKeyRef:
                  name: webapp-secret
                  key: password
