apiVersion: v1
kind: Service
metadata:
  name: webapp-nodeport-svc
  namespace: webapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080 
  selector:
    app: employee 
